### ISSUE TITLE
Validate metrics describeObject, make sure it doesn't point to non-existing objects

### ISSUE THREAD

**Issue by shaoxt** [keikoproj/cd-guard#1]
describeObject doesn't support Rollout object. 
Users should avoid to use Rollout object under "describeObject".

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: hpa-samples
  name: hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - object:
        metricName: namespace_app_pod_cpu_utilization
        targetValue: 80
        target:
          apiVersion: apps/v1
          kind: Deployment
          name: hpa-samples
      type: Object
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-samples-deployment
```
